config/routes.rb
Tmbc::Application.routes.draw do
  root "pages#welcome"
  get "thanks" => "pages#thanks"
  get "contact" => "pages#contact"
  get "about" => "pages#about"
  get "inspire" => "pages#inspire"
  get "boxes" => "pages#boxes"
  get "tri1" => "pages#tri1"
  get "tri2" => "pages#tri2"
  get "tri3" => "pages#tri3"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end

  def thanks
  end

  def contact
  end

  def about
  end

  def boxes
  end

  def inspire
  end

  def tri1
  end

  def tri2
  end

  def tri3
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_feature1.html.erb
<div style="background: #ecf0f1; color: #34495e;">
<br><hr class="featurette-divider">
<div class="row featurette">
  <div class="col-sm-7">
    <h2 class="featurette-heading">The Best Skin Ever<span class="text-muted"> <br>(Best Skin Ever)</span></h2>
    <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
  </div>
  <div class="col-sm-5">
    <img class="featurette-image img-responsive" src="https://s3.amazonaws.com/dallinmckay/SiteIMG/skinbox1.jpg" alt="Skin Box">
  </div>
</div>

<hr class="featurette-divider">

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">The Mommy Box Co</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "home", root_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_info.html.erb
<div style="background: #ecf0f1; color: #34495e;">
<div class="container">
<br><br><br><br>
  <div class="row">
    <div class="col-md-6">
      <h2>Pregnancy is hard</h2><br>
      <p class="lead">At The Mommy Box Company, we promise to be honest. Sure you'll look beautiful during your pregnancy, but you'll also be sick & swollen, and a lot of other things most people don't mention. Our boxes will contain all the details about what you can really expect from pregnancy.</p>
      <br><br>
    </div>
   <div class="col-md-6">
      <h2>We help you enjoy it.</h2><br>
      <p class="lead">But we don't just inform. The boxes we send out are tailored for each month of pregnancy; along with tons of information, each box also contains essentials (think nausea candies & skin cream), and some very needed pampering (think bath salts and chocolate). </p><br><br>
   </div>
<!--     <div class="col-md-6">
      <h2>So you can be YOU</h2>
      <p class="lead"></p>
    </div>-->
  </div>
  <br>
</div>

app/views/layouts/_order.html.erb
<!--cover page-->
<div class="site-wrapper" style="background: #3d566e;">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div class="inner cover">
      <br><br>
      <h1>Choose your current month of pregnancy</h1>
        <div class="row">
        <div class="col-sm-1 col-sm-offset-2">
        <h2><%= link_to "1", about_path %>
        </div>
        <div class="col-sm-1">
        <h2><%= link_to "1", about_path %>
        </div>
        <div class="col-sm-1">
        <h2><%= link_to "1", about_path %>
        </div>
        <div class="col-sm-1">
        <h2><%= link_to "1", about_path %>
        </div>
        <div class="col-sm-1">
        <h2><%= link_to "1", about_path %>
        </div>
        <div class="col-sm-1">
        <h2><%= link_to "1", about_path %>
        </div>
        <div class="col-sm-1">
        <h2><%= link_to "1", about_path %>
        </div>
        <div class="col-sm-1">
        <h2><%= link_to "1", about_path %>
        </div>
        </div><!--row-->
      </div><!--inner cover-->
    </div><!--container-->
  </div><!--wrapper-inner-->
</div><!--wrapper-->
<!--end of cover page-->

app/views/layouts/_signup.html.erb
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//themommybox.us8.list-manage.com/subscribe/post?u=65849e3a69d4c6c93217b813c&amp;id=5f4002b243" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
	<h2>Get a sweet discount when we launch!</h2>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address </label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_65849e3a69d4c6c93217b813c_5f4002b243" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</form>
</div>

<!--End mc_embed_signup-->

app/views/layouts/_trimesters.html.erb
<div class="container">
<br><br><br><br>
  <div class="row">
    <div class="col-md-4">
      <h2>The Beginning Trimester</h2><br>
      <p class="lead">The beginning</p><br><br>
    </div>
    <div class="col-md-4">
    	<h2>Second Trimester</h2><br>
    	<p class="lead"> Another Heading </p><br><br>
    </div>
   	<div class="col-md-4">
      <h2>Final Trimester.</h2><br>
      <p class="lead">The End </p><br><br>
  	</div>
  </div>
<!--     <div class="col-md-6">
      <h2>So you can be YOU</h2>
      <p class="lead"></p>
    </div>-->
  </div>
  <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>

  <meta name="google-site-verification" content="NM-dgsGbp_uM-bWNL3nyWIEGaf7yChq1RiSGISjyC5Y" />
  <meta name="p:domain_verify" content="9b70b9fe48c6f6a4c56a70a953a3e43e"/>

  
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48086032-2', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');
	</script>


</head>
<!--pinterest-->
<script type="text/javascript" async  data-pin-hover="true" src="//assets.pinterest.com/js/pinit.js"></script>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<title>About The Mommy Box Company | A Pregnancy Gift for Original Mothers</title>
<meta content='The first company to deliver a package solely designed with the pregnant women in mind.' property='og:description'>
<meta content='The Mommy Box Co.' property='og:title'>

<%= render 'layouts/order' %>

app/views/pages/boxes.html.erb
<title>Pregnancy Box Contents & Gift Ideas | The Mommy Box Company</title>
<meta content='The best pregnancy gift on the market - a monthly box solely for the pleasure and comfort of the pregnancy women.'>
<meta content='The Mommy Box Co.' property='og:title'>


  <div class="masthead clearfix">
    <div class="inner">
      <h3 class="masthead-brand">The Mommy Box Co</h3>
      <ul class="nav masthead-nav">
        <li><%= link_to "home", root_path %></li>
        <li class="active"><%= link_to "boxes", boxes_path %></li>
        <li><%= link_to "inspiration", inspire_path %></li>
        <li>
          <button class="btn btn-warning" data-toggle="modal" data-target="#myModal">Reserve Your Discount &raquo;</button>
        </li>
      </ul>
    </div>
  </div>
  <div class="container">
  <center><br><br><br>
    <div class="row">
    <div class="col-md-8 col-md-offset-2">
    <h1 style="font-size: 50px;">Get the skinny on our fat boxes <hr> </h1><br>
    </div>
    <div class="col-md-10 col-md-offset-1">
    <p class="lead">Each box is different, but every trimester has a theme. Explore each of the trimesters below to get an idea of what is included in the boxes. </p>
  </div>
  </center>
  </div>
<%= render 'layouts/trimesters' %>

app/views/pages/contact.html.erb
<title>Pregnancy Questions & Facts | Contact The Mommy Box Company</title>
<meta content='Contact The Mommy Box Company - Delivering the best pregnancy & push presents to pregnant mothers.'>
<meta content='The Mommy Box Co.' property='og:title'>

  <div class="masthead clearfix">
    <div class="inner">
      <h3 class="masthead-brand">The Mommy Box Co</h3>
      <ul class="nav masthead-nav">
        <li><%= link_to "home", root_path %></li>
        <li><%= link_to "boxes", boxes_path %></li>
        <li><%= link_to "inspiration", inspire_path %></li>
        <li>
          <button class="btn btn-warning" data-toggle="modal" data-target="#myModal">Order &raquo;</button>
        </li>
      </ul>
    </div>
  </div>
  <div class="container">
  <center><br><br><br>
    <div class="row">
    <div class="col-md-8 col-md-offset-2">
    <h1 style="font-size: 50px;">CONTACT &nbsp THE &nbsp PREGNANCY &nbsp VETERANS <hr> </h1><br>
    </div>
    <div class="col-md-10 col-md-offset-1">
    <p class="lead">Let us know your thoughts! We want to be the best there is, so please give us your honest, un-censored feedback, criticism, or praise. Or, if you need advice or just someone to talk to about your pregnancy, we're here for that too! Honestly.</p>
  </div>
  </center>
  <div class="row">
    <div class="col-sm-10 col-sm-offset-2">
<!--contact form-->
<div id="wufoo-m1kr808y1pl7i5q">
Fill out my <a href="https://plonkerspopcorn.wufoo.com/forms/m1kr808y1pl7i5q">online form</a>.
</div>
<div id="wuf-adv" style="font-family:inherit;font-size: small;color:#a7a7a7;text-align:center;display:block;"><a href="http://www.wufoo.com/form-builder/"></a></div>
<script type="text/javascript">var m1kr808y1pl7i5q;(function(d, t) {
var s = d.createElement(t), options = {
'userName':'plonkerspopcorn',
'formHash':'m1kr808y1pl7i5q',
'autoResize':true,
'height':'443',
'async':true,
'host':'wufoo.com',
'header':'hide',
'ssl':true};
s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'www.wufoo.com/scripts/embed/form.js';
s.onload = s.onreadystatechange = function() {
var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
try { m1kr808y1pl7i5q = new WufooForm();m1kr808y1pl7i5q.initialize(options);m1kr808y1pl7i5q.display(); } catch (e) {}};
var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
})(document, 'script');</script>

<!--end of contact form-->
    </div>
  </div>

app/views/pages/inspire.html.erb
<title>Pregnancy Photography Inspiration | The Mommy Box Company</title>
<meta content='Pregnancy Inspiration - A compilation of our favorite pregnancy images of classy & original mothers.'>
<meta content='The Mommy Box Co.' property='og:title'>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-542182e35f4d9e1e"></script>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="color: #34495e;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Let's Do This!</h4>
      </div>
      <div class="modal-body">
        <%= render 'layouts/signup' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div style="background-color: #290029;">
	<div class="masthead clearfix">
    <div class="inner">
      <h3 class="masthead-brand">The Mommy Box Co</h3>
      <ul class="nav masthead-nav">
        <li><%= link_to "home", root_path %></li>
        <li>
          <button class="btn btn-warning" data-toggle="modal" data-target="#myModal">Reserve Your Discount &raquo;</button>
        </li>
      </ul>
    </div>
  </div>
	<div class="container">
	<center><br><br><br>
		<div class="row">
		<div class="col-md-8 col-md-offset-2">
		<h1 style="font-size: 50px;">#OriginalMom(s) <br> YOU are our inspiration!<hr> </h1><br>
		</div>
		<div class="col-md-10 col-md-offset-1">
		<p class="lead">Here are some of our favorite #OriginalMom tagged photos. Tag your own photos with #OriginalMom and we might add you to our wall of inspiration. We may even reach out to you and feature you in our upcoming stories</p>

	</div>
	</div>
	</center>
<div class="container">

<img class="boxed" src="https://s3.amazonaws.com/TMBCo/NicoleG-23+B%26W.jpg" alt="The Mommy Box Co. - Pregnancy Photography #originalmom Nicole" style="width: 80%;">

<img class="boxed" src="https://s3.amazonaws.com/TMBCo/NicoleG-13+B%26W.jpg" alt="The Mommy Box Co. - Pregnancy Photography #originalmom Nicole" style="width: 80%;">

<img class="boxed" src="https://s3.amazonaws.com/TMBCo/NicoleG-27+B%26W.jpg" alt="The Mommy Box Co. - Pregnancy Photography #originalmom Nicole" style="width: 80%;">

<img class="boxed" src="https://s3.amazonaws.com/TMBCo/NicoleG-32.jpg" alt="The Mommy Box Co. - Pregnancy Photography #originalmom Nicole" style="width: 80%;">

<img class="boxed" src="https://s3.amazonaws.com/TMBCo/NicoleG-33+B%26WFLIP.jpg" alt="The Mommy Box Co. - Pregnancy Photography #originalmom Nicole" style="width: 80%;">

<img class="boxed" src="https://s3.amazonaws.com/TMBCo/NicoleG-36+B%26W.jpg" alt="The Mommy Box Co. - Pregnancy Photography #originalmom Nicole" style="width: 80%;">

<img class="boxed" src="https://s3.amazonaws.com/TMBCo/NicoleG-4.jpg" alt="The Mommy Box Co. - Pregnancy Photography #originalmom Nicole" style="width: 80%;">

<img class="boxed" src="https://s3.amazonaws.com/TMBCo/NicoleG-43+B%26W.jpg" alt="The Mommy Box Co. - Pregnancy Photography #originalmom Nicole" style="width: 80%;">

<img class="boxed" src="https://s3.amazonaws.com/TMBCo/NicoleG-12+B%26W.jpg" alt="The Mommy Box Co. - Pregnancy Photography #originalmom Nicole" style="width: 80%;">

</div>
</div>
</div>

app/views/pages/thanks.html.erb
<meta charset="UTF-8">
<meta http-equiv="refresh" content="5; url=http://themommybox.co">
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand">The Mommy Box Co</h3>
        </div>
      </div>
      <div class="inner cover">
      <br><br>
        <h1 class="cover-heading" style="font-size: 100px;">Thank You!</h1>
<!--        <p class="lead">Just confirm via email and we'll be sure to send you that discount when we launch!</p> -->
      </div>
      	<div class="mastfoot">
      		<p>This page will self destruct in 4 seconds...and redirect you to <a href='http://themommybox.co'>our front page.</a></p>
      	</div>
    </div>
  </div>
</div>
<script>
setTimeout(function () {
   window.location.href = "http://themommybox.co";}, 4000);
</script>

app/views/pages/tri1.html.erb
Trimester #1 Box Contents.

app/views/pages/tri2.html.erb
tri2

app/views/pages/tri3.html.erb
tri3

app/views/pages/welcome.html.erb
  <title>The Mommy Box Company | The Best Gift For Pregnant Mothers</title>
  <meta content='The best gift for a pregnant mom. A monthly box of essentials, information, and pampering.'>
<meta content='The Mommy Box Co.' property='og:title'>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="color: #34495e;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Let's Do This!</h4>
      </div>
      <div class="modal-body">
        <%= render 'layouts/signup' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!--cover page-->
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand">The Mommy Box Co</h3>
          <ul class="nav masthead-nav">

            <li><%= link_to "inspiration", inspire_path %></li>
            <li>

              <button class="btn btn-warning" data-toggle="modal" data-target="#myModal">Reserve Your Discount &raquo;</button>
            </li>
          </ul>
        </div>
      </div>
      <div class="inner cover">
      <br><br><br><br><br><br><br><br>
        <div class="row">
        <div class="col-sm-7 col-sm-offset-5">
        <h2>WE'RE CHANGING THE WAY WOMEN EXPERIENCE PREGNANCY</h2> 
        <p class="lead">We provide the essentials, information, and some seriously needed pampering, all in one monthly box. <br><strong>Launching soon!</strong></p>
      </div>
      </div>
      </div>
    </div>
  </div>
</div>
<!--end of cover page-->
<%= render 'layouts/feature1' %>
<br><br><br>
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Claim Your Discount
</button>
<br><br><br><br><br><br><br>